[platformio]
src_dir = src

;[env:rpi]
;platform = raspberrypi
;board = pico
;framework = arduino
;lib_deps =
;    https://github.com/mavlink/c_library_v2.git
;    https://github.com/UAVCAN/libcanard.git
;build_flags =
;    -DARDUINO_ARCH_RP2040=0
;monitor_speed = 115200
;upload_port = /dev/ttyUSB0

;[env:raspberrypi_zero]
;platform = linux_arm
;board = raspberrypi_zero
;framework = arduino
;lib_deps =
;    https://github.com/mavlink/c_library_v2.git
;    https://github.com/UAVCAN/libcanard.git
;build_flags =
;    -DARDUINO_ARCH_RP2040=0
;monitor_speed = 115200
;upload_port = /dev/ttyUSB0

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
   https://github.com/mavlink/c_library_v2.git
    https://github.com/UAVCAN/libcanard.git
    CAN
    Ethernet
    WiFi
monitor_speed = 115200
upload_port = /dev/ttyUSB0


; [env:stm32]
; platform = ststm32
; board = nucleo_f103rb
; framework = arduino
; lib_deps =
;     https://github.com/mavlink/c_library_v2.git
;     https://github.com/UAVCAN/libcanard.git
;     STM32duino/CAN
; monitor_speed = 115200
;upload_port = /dev/ttyUSB0

#mavlink/c_library_v2
#uavcan/libcanard